<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.37027391 0.34300782 0.8388346  ... 0.79612561 0.19774542 0.73393608]
 [0.63096854 0.40756861 0.25967852 ... 0.88753336 0.40482889 0.37428943]
 [0.13302146 0.03228776 0.92507461 ... 0.3742821  0.561312   0.88186774]
 ...
 [0.15864675 0.45144874 0.97240278 ... 0.51800228 0.0918879  0.8942154 ]
 [0.48062891 0.88764017 0.11516844 ... 0.74321867 0.63510318 0.98544938]
 [0.57275249 0.08570893 0.64546274 ... 0.91568221 0.50608739 0.17998144]]
[[0.90902596 0.62877039 0.08377833 ... 0.87641561 0.308667   0.58189267]
 [0.39204101 0.34239014 0.43807537 ... 0.83600144 0.16604489 0.9715317 ]
 [0.14868251 0.51833425 0.26821361 ... 0.57253728 0.90886449 0.86615238]
 ...
 [0.09534933 0.51858431 0.5806257  ... 0.60895433 0.33774349 0.76422191]
 [0.59094881 0.13470946 0.65831032 ... 0.16213532 0.31435204 0.90901069]
 [0.12582138 0.94090677 0.17320623 ... 0.46821039 0.87135114 0.18295062]]


In [3]:
def mult(a, b):
    """
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    n = len(a)
    res_matrix = [[0 for i in range(n)] for j in range(n)]

    for i in range(n):
      for j in range(n):
        for z in range(n):
            res_matrix[i][j] += (a[i][z] * b[z][j])
    return res_matrix

In [4]:
def np_mult(a, b):
    """
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a.dot(b)

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 725 ms, sys: 0 ns, total: 725 ms
Wall time: 729 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.6 ms, sys: 4.13 ms, total: 5.74 ms
Wall time: 9.61 ms


In [7]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.66082111 0.88852082 0.14404952] [0.37671967 0.98197909 0.51473985]


In [13]:
def scalar_product(a, b):
    """
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

In [14]:
def np_scalar_product(a,b):
    """
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """
    a = np.array(a)
    b = np.array(b)
    return a.dot(b)

In [15]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 26 µs, sys: 4 µs, total: 30 µs
Wall time: 34.1 µs
CPU times: user 48 µs, sys: 0 ns, total: 48 µs
Wall time: 52.2 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [21]:
def np_diag_2k(a):
    """
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    diag = np.diag(a)
    even_diag = diag[diag % 2 == 0]
    result = np.sum(even_diag) if len(even_diag) > 0 else 0
    return result

In [22]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 5, 1, 2, 4],
       [2, 8, 5, 1, 1],
       [9, 8, 5, 9, 2],
       [6, 2, 3, 4, 7],
       [9, 2, 4, 7, 7]])

In [23]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 245 µs, sys: 0 ns, total: 245 µs
Wall time: 318 µs


14

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​

In [27]:
def cumsum(A):
    """
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    return np.cumsum(A, axis=-1)

In [28]:
# зададим некоторую последовательность и проверим ее на вашей функции.
A = sps.uniform.rvs(size=10**3)

%time S2 = cumsum(A)

CPU times: user 62 µs, sys: 0 ns, total: 62 µs
Wall time: 66.3 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [29]:
from copy import copy
def np_transformation(X, a=1):
    """
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке,
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    Y = X.copy()
    Y[:, 1::2] = a
    Y[:, 0::2] = Y[:,0::2]**3
    Y = Y[:, ::-1]
    return np.hstack((X, Y))

In [30]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 1.13 ms, sys: 14 µs, total: 1.14 ms
Wall time: 1.15 ms


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [31]:
def np_encode(a):
    """
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор
    repetitions добавляет длины последовательностей подряд идущих повторений.
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    mask = np.concatenate(([True], a[1:] != a[:-1]))

    unique_values = a[mask]

    counts = np.diff(np.where(np.append(mask, True)))[0]

    return unique_values, counts

In [32]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 1.73 ms
